Replacing an error message 415 #2
profcomff/print-tgbot pull request #84
Opened 2024-04-21 20:27 UTC by iskomir

2024-04-21 20:30 UTC, grigoriev-semyon requested changes

2024-04-21 20:30 UTC, grigoriev-semyon commented on src/handlers.py
> -        text=ans.print_err,
а почему это не в ветке 415?

2024-04-21 20:41 UTC, annndruha commented on src/handlers.py
> -        text=ans.print_err,
Плюс. Это ответ на все остальные коды ошибок. Здесь не должно идти речи про формат файла.

2024-04-21 20:42 UTC, annndruha commented
В слитом MR уже всё должно быть нормально

2024-04-22 02:02 UTC, annndruha commented on src/handlers.py
>      logging.warning(f'{log_actor(update)} print unknown error')
Если уж очень хочется занести ответ на остальные коды ошибок в ветку else, то тогда последний logging нужно туда же занести и аккуратно убрать return`ы из ветвей.

2024-04-22 05:21 UTC, grigoriev-semyon requested changes

2024-04-22 05:21 UTC, grigoriev-semyon commented on src/handlers.py
> +    else:
Не вижу никакого смысла в этих изменениях
Меня надо запрос rfile а в этом запросе просто откатить изменения прошлого ПРа

2024-04-22 05:22 UTC, grigoriev-semyon commented on src/handlers.py
>      logging.warning(f'{log_actor(update)} print unknown error')
Не нужно ничего тут менять, оставьте эту часть кода в покое
Нужно убрать из этого запроса обработку 415 и перенести во вложенный

2024-04-29 18:20 UTC, grigoriev-semyon approved these changes

2024-04-29 18:24 UTC, merged